version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockers/Dockerfile
    privileged: true
    volumes:
      - .:/app/python
    links:
      - mysql
  mysql:
    image: mysql:5.7
    volumes:
      - ./dockers/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
